config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :properties do
    member do
      get :owner_bookings
    end
  end

  get 'my_bookings', to:'bookings#my_bookings'
  get 'allprop', to:'properties#allprop'
  # get 'property bookings', to:'bookings#owner_booking'

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html9
  # Defines the root path route ("/")
  root "homes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
	belongs_to :user
	belongs_to :property

  validates :start_date, :end_date, presence: true
end

app/models/property.rb
class Property < ApplicationRecord
	belongs_to :user
	has_many :bookings ,dependent: :delete_all

  validates :property_name, :address, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
	has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :roles
  has_many :properties
  has_many :bookings

  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates :name, :email,:account, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, :except => [:index]

	before_action :config_params, if: :devise_controller?


	def after_sign_in_path_for(resource)
       
        if current_user.roles.first.role_name == "customer"
            return allprop_path
        else 
            return properties_path
        end 
    end

	protected
  		def config_params
     		devise_parameter_sanitizer.permit(:sign_up,keys:[:name, :email, :account,:encrypted_password, :role_ids])
  		end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]

  # GET /bookings or /bookings.json
  def index
     if user_signed_in?
      @bookings = Booking.all
      # flash.now[:notice] = "We have exactly #{@bookings.size} bookings available."
    else
      redirect_to '/'
    end
  end


  def my_bookings
    if user_signed_in?
      @mybookings = current_user.bookings
      flash.now[:notice] = "You've made exactly #{@mybookings.size} bookings."
    end
  end


  # GET /bookings/1 or /bookings/1.json
  def show
  end


  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  def owner_booking
      @booking = Booking.find(params[:property_id])
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json

  # if @message.save
  #   flash.now[:notice] = 'Message sent!'
  # else
  #   flash.now[:alert] = 'Error while sending message!'
  # end

  def create
    @booking = Booking.new(booking_params)
    # @property  = Property.where(id: params[:booking][:property_id]).first

    if @booking.start_date && @booking.end_date

      if(@booking.start_date >= Date.today && @booking.end_date > @booking.start_date)
        logger.info "this is correct format....."

        if current_user.roles.last.role_name == "customer"
          @booking.user_id = current_user.id
          @booking.price = @booking.property.price

          respond_to do |format|
            if @booking.save
              format.html { redirect_to booking_url(@booking), notice: "Booking was successfully created." }
              format.json { render :show, status: :created, location: @booking }
            else
              format.html { render :new, status: :unprocessable_entity }
              format.json { render json: @booking.errors, status: :unprocessable_entity }
            end
          end
        else logger.info "owner can not create booking"
        end

      else
         flash[:notice] = "wrong format "
         return redirect_to new_booking_path
         # flash.now[:alert] = "wrong format"

        logger.info "this is wrong format....."
      end
    else
         # flash.now[:notice] = "please enter in correct format"
         flash[:notice] = "please select something format"
         redirect_to new_booking_path
    end


    
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "Booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      if !user_signed_in?
        redirect_to "/"
      end
      @booking = Booking.find(params[:id])
    end


    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:price, :start_date, :end_date, :property_id)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index

  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show edit update destroy owner_bookings]

  # GET /properties or /properties.json
  def index
    if user_signed_in?
      @properties = current_user.properties.all
    else
      redirect_to '/'
    end
  end

  def allprop
    @property = Property.where(inactive:false)
    @user = current_user.name
  end

  # GET /properties/1 or /properties/1.json
  def show
  end

  def owner_bookings
    @bookings = @property.bookings
  end

  
  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties or /properties.json
  def create
    @property = Property.new(property_params)
    @property.user_id=current_user.id
    respond_to do |format|
      if @property.save
        format.html { redirect_to property_url(@property), notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to property_url(@property), notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:property_name, :address, :price, :pin, :inactive)
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">
  <p>
    <strong>Price:</strong>
    <%= booking.property.price %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= booking.start_date %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= booking.end_date %>
  </p>

 <!--  <p>
    <strong>Status:</strong>
    <%#= booking.status %>
  </p> -->

</div>

app/views/bookings/_form.html.erb
<%= form_with(model: booking) do |form| %>
  <% if booking.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date %>
  </div>

  <div>
    <%= form.label :end_date, style: "display: block" %>
    <%= form.date_field :end_date %>
  </div>
  <!-- <p style="color: red;"><%= notice %></p> -->


  <div>
    <%= form.hidden_field :property_id, value: params[:property_id_for_booking] %>
  </div>
  <div>
    <%#= form.hidden_field :price, value: params[:price]%>
  </div>

<br>
  <div>
    <%= form.submit %>
  </div>


<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Show this booking", @booking %>
  <%#= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/index.html.erb
<!-- <p style="color: green"><%= notice %></p> -->

<h1>Bookings</h1>

<div id="bookings">
  <% @bookings.each do |booking| %>
    <%= render booking %>
    <p>
      <%= link_to "Show this booking", booking %>
    </p>
  <% end %>
</div>

<%= link_to "New booking", new_booking_path %>

app/views/bookings/my_bookings.html.erb
<h1> <%= current_user.name %> Bookings</h1>
<p style="color: green"><%= notice %></p>

<!-- 
<div id="mybookings">
  <#% @mybookings.each do |booking| %>
    <%#= render booking %>
    <p>
      <%#= link_to "Show this booking", booking %>
    </p>
  <#% end %>
</div>
 -->

<div class="flex">
<%= link_to "New booking", allprop_path,:class => "btn btn-danger" %>
</div>


<table class="table table-bordered">
    <thead>
      <tr class="table-danger">
        <th>property name</th>
        <th> price </th>
        <th> start date</th>
        <th> end date</th>
      </tr>
    </thead>
   <% @mybookings.each do |booking| %>
    <tbody>
      <tr>
        <td><%= booking.property.property_name %></td>
        <td><%= booking.price %></td>
        <td><%= booking.start_date %></td>
        <td><%= booking.end_date %></td>
        
      </tr>
    </tbody>
    <%end%>
  </table>

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= render "form", booking: @booking %>

app/views/bookings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @booking %>

<div>
  <%= link_to "Edit this booking", edit_booking_path(@booking) %>
  <%#= link_to "Back to bookings", bookings_path %>

  <%#= button_to "Destroy this booking", @booking, method: :delete %>
</div>

<br>
<%= button_to 'property listing', allprop_path, method: :get%>
<br>
<%= button_to 'sign out', destroy_user_session_path, method: :delete%>

app/views/homes/index.html.erb
<h1>Homes Page </h1>
<p>click below to Sign in or Sign out</p>

<% if  current_user %>
    <%= button_to 'sign out', destroy_user_session_path,:class=>"btn btn-danger", method: :delete%>
    <!-- <button>hi</button> -->
    <% else %>
    <%= link_to 'sign in' ,new_user_session_path,:class => "btn btn-success", method: :get %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotel3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>

  </body>
</html>

app/views/properties/_form.html.erb
<%= form_with(model: property) do |form| %>
  <% if property.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :property_name, style: "display: block" %>
    <%= form.text_field :property_name %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :pin, style: "display: block" %>
    <%= form.number_field :pin %>
  </div>

  <div>
    <%= form.label :property_inactive?, style: "display: block" %>
    <%#= form.check_box :inactive %>
    <%= form.check_box :inactive, {checked: false, checked_value:true, unchecked_value: false}  %>

    <%#= form.check_box :inactive, { checked: true }, 'yes', 'no'  %>

  </div>

  <br>
  <br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/properties/_property.html.erb
<div id="<%= dom_id property %>">
  <p>
    <strong>Property name:</strong>
    <%= property.property_name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= property.address %>
  </p>

  <p>
    <strong>price:</strong>
    <%= property.price %>
  </p>

  <p>
    <strong>pin:</strong>
    <%= property.pin %>
  </p>

</div>

app/views/properties/allprop.html.erb
<h1>   Property listing for  <b> <%= @user %></b></h1>
<span class="badge bg-success">only active properties</span>


<div id="properties">

	<br>

	<div  class="d-flex justify-content-between">
  		<div class="mx-5">
  			<%= button_to 'my bookings', my_bookings_path,:class => "btn btn-info"	, method: :get , message:'this user has' %>
  		</div>
  		<div class="mx-5">
  			<%= button_to 'sign out',destroy_user_session_path,:class => "btn btn-danger", method: :delete %>
  		</div>
	</div>
	
	<table class="table table-bordered">
		<thead class="table-dark">
			<tr>
				<th>property name  </th>
				<th> address</th>
				<th> price</th>
				<th> pin code</th>
				<th> book here </th>
			</tr>
		</thead>

		<% @property.each do |p| %>
		<tbody>
			<tr>
				<td><%= p.property_name %></td>
				<td><%= p.address %></td>
				<td><%= p.price %></td>
				<td><%= p.pin %></td>
				<td><%= link_to "Book Now", new_booking_path(property_id_for_booking: p.id) %></td>
			</tr>
		</tbody>
		<%end%>
	</table>
		
</div>

app/views/properties/edit.html.erb
<h1>Editing property</h1>

<%= render "form", property: @property %>

<br>

<div>
  <%= link_to "Show this property", @property %> |
  <%= link_to "Back to properties", properties_path %>
</div>

app/views/properties/index.html.erb
<p style="color: green"><%= notice %></p>

<h1> <%= current_user.name %> Properties</h1>
<%= button_to 'sign out', destroy_user_session_path,:class => "btn btn-danger", method: :delete%>

<!-- <div id="properties">
  <%# @properties.each do |property| %>
    <%#= render property %>
    <p>
      <%#= link_to "Show this property", property %>
      <%#= link_to "owner booking", owner_bookings_property_path(property.id) %>
    </p>
  <%#end %>

</div> -->

<table class="table">
    <thead>
      <tr>
        <th>property name</th>
        <th> address</th>
        <th> price</th>
        <th> pin code</th>
      </tr>
    </thead>
  <% @properties.each do |p| %>
    <tbody>
      <tr>
        <td><%= p.property_name %></td>
        <td><%= p.address %></td>
        <td><%= p.price %></td>
        <td><%= p.pin %></td>
        <td><%= link_to "Show property", p,:class => "btn btn-sm btn-info" %></td>
        <td><%= link_to "owner booking", owner_bookings_property_path(p.id),:class => "btn btn-sm btn-warning" %></td>

      </tr>
    </tbody>
    <%end%>
  </table>
  <%= link_to "+New property", new_property_path,:class => "btn btn-success" %>
  

app/views/properties/new.html.erb
<h1>New property</h1>

<%= render "form", property: @property %>

<br>

<div>
  <%= link_to "Back to properties", properties_path %>
</div>

app/views/properties/owner_bookings.html.erb
<h1>bookings of this property</h1>

<div id="bookings">


  <table class="table">
    <thead>
      <tr class="table table-primary">
        <td> Property Name </td>
        <td> Price </td>
        <td> From </td>
        <td> TO </td>
      </tr>
    </thead>
    <tbody>
      <% @bookings.each do |b| %>
      <tr>
        <td> <%= b.property.property_name %> </td>
        <td> <%= b.price %> </td>
        <td> <%= b.start_date %> </td>
        <td> <%= b.end_date %> </td>
      </tr>
      <% end %>

    </tbody>
  </table>

  <%= button_to 'back', properties_path,:class => "btn btn-info"  , method: :get%>

   
</div>

app/views/properties/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @property %>

<div>
  <%= link_to "Edit this property", edit_property_path(@property) %> ||
  <%= link_to "Back to properties", properties_path %>

  <%= button_to "Destroy this property", @property, method: :delete %>
</div>